#define PATH_A "exec/pa"
#define PATH_B "exec/pb"
#define PATH_C "exec/pc"
#define PATH_D "exec/pd"
#define FILES_PATH "files/log.txt"
#define MODEL_A "A"
#define MODEL_B "B"
#define MODEL_C "C"
#define MODEL_A_PDF "/MODELOA.pdf"
#define MODEL_B_PDF "/MODELOB.pdf"
#define MODEL_C_PDF "/MODELOC.pdf"
#define MODEL_PATH "examModels/"
#define PC_MSG "Mark you should obtain in this new exam to pass is:"
#define NEED_MARK "/Needed_mark.txt"